name: Import Followers Grid from Generator Repo

on:
  schedule:
    - cron: '30 18 * * *'  # 12:00 AM IST daily
  workflow_dispatch:

jobs:
  update-followers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Profile Repo
        uses: actions/checkout@v4

      - name: Download followers.html from generator repo (public)
        run: |
          curl -s -o followers.html https://raw.githubusercontent.com/EchoSingh/github-followers-grid/main/followers.html

      - name: Replace followers section in README.md
        run: |
          START="<!-- FOLLOWERS-START -->"
          END="<!-- FOLLOWERS-END -->"
          HTML=$(cat followers.html)

          awk -v html="$HTML" -v start="$START" -v end="$END" '
          BEGIN { found=0 }
          {
            if ($0 ~ start) {
              print $0
              print html
              found=1
              next
            }
            if ($0 ~ end) { found=0 }
            if (!found) print $0
          }' README.md > README.tmp && mv README.tmp README.md

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update followers section [bot]" || echo "No changes"
          git push
