# GitHub Metrics

name: GitHub Metrics

on:
  workflow_dispatch:
  push:
    branches: [master, main]
  schedule:
    - cron: '30 0 * * *'

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          # The filename for the output SVG
          filename: assets/github-metrics-${{ github.ref_name }}.svg

          # Personal Access Token (PAT) for access to private data
          token: ${{ secrets.METRICS_TOKEN }}

          # Committer token is used to create the commit
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # A friendly message for the commit
          committer_message: "Updated GitHub Metrics"


          # Use a dark, sleek theme. You can change this to `classic` or `markdown` if you prefer.
          template: classic
          config_timezone: Asia/Kolkata
          config_padding: 10
          config_animations: yes

          # Display config and order
          config_order: |
            base.header,
            introduction,
            isocalendar,
            habits,
            base.activity+community,
            lines,
            discussions,
            leetcode,
            topics,
            anilist,
            base.repositories,
            pagespeed

          # ------------------------------------
          # Plugins Configuration
          # ------------------------------------

          # Isometric calendar (last 6 months of contributions)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # Base content
          base: header, activity, community, repositories
          base_indepth: yes
          base_hireable: no

          # Plugin: Introduction
          plugin_introduction: yes

          # Plugin: Lines
          plugin_lines: yes
          plugin_lines_sections: base
          plugin_lines_repositories_limit: 5
          plugin_lines_history_limit: 2

          # Plugin: PageSpeed
          plugin_pagespeed: yes
          plugin_pagespeed_screenshot: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: "https://adi-pf.vercel.app/"

          # Plugin: Habits
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no

          # Plugin: Stars
          #plugin_stars: yes
          plugin_stars_limit: 1

          # Plugin: Topics
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: icons

          # Plugin: Discussions
          plugin_discussions: yes

          # Plugin: Screenshot (XKCD)
          #plugin_screenshot: yes
          plugin_screenshot_title: XKCD of the day
          plugin_screenshot_url: https://xkcd.com
          plugin_screenshot_selector: "#comic img"

          # Plugin: Anilist (Anime/Manga)
          plugin_anilist: yes
          plugin_anilist_user: adi2603
          plugin_anilist_medias: manga
          plugin_anilist_sections: favorites, characters
          plugin_anilist_limit: 1
          plugin_anilist_limit_characters: 1

          # Plugin: People
          #plugin_people: yes
          plugin_people_types: followers

          # Plugin: LeetCode
          plugin_leetcode: yes
          plugin_leetcode_user: rayo_n

          # Plugin: RSS
          #plugin_rss: yes
          plugin_rss_source: https://news.ycombinator.com/rss
          plugin_rss_limit: 4
