name: Github Metrics

on:
  workflow_dispatch:
  push:
    branches: [master, main]
  schedule:
    - cron: 30 6 * * * # Runs daily at (12:00 AM IST)

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics-${{ github.ref_name }}.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_message: "👾👾👾👾"

          # Base configuration
          base: activity, community, repositories, metadata, commits
          base_skip: header

          # Plugin: Introduction
          plugin_introduction: yes
          plugin_introduction_title: yes

          # Plugin: Lines
          plugin_lines: yes
          plugin_lines_sections: base
          plugin_lines_repositories_limit: 5
          plugin_lines_history_limit: 2

          # Plugin: WakaTime
          plugin_wakatime: yes
          plugin_wakatime_sections: time, languages, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}

          # Plugin: Achievements
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact
          plugin_achievements_limit: 10

          # Plugin: Stargazers
          plugin_stargazers: yes
          plugin_stargazers_charts: yes

          # Plugin: Isocalender
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # Plugin: Stars
          plugin_stars: yes
          plugin_stars_limit: 1


          # Hobbies
          # Anime 
          plugin_anilist: yes
          plugin_anilist_user: adi2603
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, watching
          plugin_anilist_limit: 1

          # Peoples
          plugin_people: yes
          plugin_people_types: followers
          

          # Configuration order
          config_order: |
            introduction,
            base.activity+community,
            base.repositories,
            lines,
            wakatime,
            achievements,
            stargazers,
            anilist,
            calendar,
            stars,
            people
