name: GitHub Metrics

on:
  workflow_dispatch:
  push:
    branches: [master, main]
  schedule:
    - cron: '30 0 * * *' # Runs daily at 06:00 AM UTC (12:00 AM IST)

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics-${{ github.ref_name }}.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_message: "^_^"

          # Base config
          base: header
          base_indepth: no
          base_hireable: no

          # Plugin: Introduction
          plugin_introduction: yes

          # Plugin: Lines
          plugin_lines: yes
          plugin_lines_sections: base
          plugin_lines_repositories_limit: 5
          plugin_lines_history_limit: 2

          # Plugin: PageSpeed
          plugin_pagespeed: yes
          plugin_pagespeed_screenshot: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: "https://adi-pf.vercel.app/"

          # Plugin: Habits
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          config_timezone: Asia/Kolkata

          # Plugin: Isocalendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # Plugin: Stars
          plugin_stars: yes
          plugin_stars_limit: 1

          # Plugin: Topics
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: icons

          # Plugin: Discussions
          plugin_discussions: yes

          # Plugin: Screenshot (XKCD)
          plugin_screenshot: yes
          plugin_screenshot_title: XKCD of the day
          plugin_screenshot_url: https://xkcd.com
          plugin_screenshot_selector: "#comic img"

          # Plugin: Anilist (Anime/Manga)
          plugin_anilist: yes
          plugin_anilist_user: adi2603
          plugin_anilist_medias: manga
          plugin_anilist_sections: favorites, characters
          plugin_anilist_limit: 1
          plugin_anilist_limit_characters: 1

          # Plugin: People
          #plugin_people: yes
          plugin_people_types: followers

          # Plugin: LeetCode
          plugin_leetcode: yes
          plugin_leetcode_user: adi_s_r

          # Plugin: RSS
          plugin_rss: yes
          plugin_rss_source: https://news.ycombinator.com/rss
          plugin_rss_limit: 4

          # Display config and order
          config_order: |
            base.header,
            introduction,
            base.activity+community,
            base.repositories,
            habits,
            lines,
            discussions,
            stars,
            isocalendar,
            topics,
            rss,
            people,
            screenshot
