name: GitHub Metrics

on:
  schedule: [{ cron: "0 * * * *" }]  # Updates every hour
  workflow_dispatch:
  push: { branches: ["main", "master"] }

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Generate GitHub Metrics (Dark + Batman x Catppuccin)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: EchoSingh
          template: classic

          base: header, activity, community, repositories, metadata

          config_timezone: Asia/Calcutta
          config_twemoji: true
          config_gemoji: true
          config_octicon: true
          config_animations: true
          config_base64: true
          config_padding: "0,10"
          config_display: large

          filename: github-metrics-${{ github.ref_name }}.svg
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_message: "🦇 Gotham status report delivered."

          extras_css: |
            svg {
              background-color: #1e1e2e;
              font-family: "Comic Sans MS", "Comic Sans", cursive, sans-serif;
            }

            .header, .header-title, .header-subtitle {
              fill: #fab387; /* Catppuccin Mocha Peach */
              font-weight: bold;
            }

            .text-primary, .text-secondary, .text-tertiary {
              fill: #cdd6f4; /* Latte text color */
            }

            .icon, .icon * {
              fill: #f9e2af; /* Yellowish Gold accent */
            }

            .card {
              fill: #2e2e3e;
              stroke: #fab387;
              stroke-width: 1;
              rx: 6;
              ry: 6;
            }

            .card-shadow {
              filter: drop-shadow(2px 2px 5px rgba(0, 0, 0, 0.5));
            }

          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes

          plugin_anilist: yes
          plugin_anilist_user: .user.login
          plugin_anilist_medias: manga
          plugin_anilist_sections: favorites,characters
          plugin_anilist_limit: 2
          plugin_anilist_limit_characters: 1
          plugin_anilist_shuffle: yes

          plugin_gists: yes
          plugin_introduction: yes
          plugin_introduction_title: yes

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_rss: yes
          plugin_rss_source: https://news.ycombinator.com/rss
          plugin_rss_limit: 4

          plugin_stargazers: yes
          plugin_stargazers_charts: yes
          plugin_stargazers_charts_type: chartist
          plugin_stargazers_days: 14
          plugin_stargazers_worldmap: yes

          plugin_starlists: yes
          plugin_starlists_limit: 2
          plugin_starlists_limit_languages: 8
          plugin_starlists_limit_repositories: 2
          plugin_starlists_shuffle_repositories: yes
