name: GitHub Metrics

on:
  workflow_dispatch:
  push:
    branches: [main, master]
  schedule:
    - cron: 30 6 * * * # Daily at 12:00 AM IST

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate GitHub Metrics (Batman x Catppuccin)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_message: "🦇 Freshly brewed GitHub Metrics!"
          filename: github-metrics-${{ github.ref_name }}.svg
          user: EchoSingh

          config_display: large
          config_padding: "0,10"
          config_timezone: Asia/Kolkata
          config_twemoji: true
          config_gemoji: true
          config_animations: true
          config_base64: true
          config_output: svg

          extras_css: |
            /* Batman x Comic Sans styling */
            svg {
              background-color: #0f0f0f;
              font-family: "Comic Sans MS", "Comic Sans", cursive, sans-serif;
            }

            .header, .header-title, .header-subtitle {
              fill: #FFD700;
              font-weight: bold;
            }

            .text-primary, .text-secondary, .text-tertiary {
              fill: #CCCCCC;
            }

            .icon, .icon * {
              fill: #FFD700;
            }

            .card {
              fill: #1f1f1f;
              stroke: #FFD700;
              stroke-width: 1;
              rx: 6;
              ry: 6;
            }

            .card-shadow {
              filter: drop-shadow(2px 2px 4px rgba(0, 0, 0, 0.5));
            }

          config_order: |
            introduction,
            base.header,
            base.activity+community,
            base.repositories,
            habits,
            achievements,
            lines,
            stars,
            isocalendar,
            topics,
            rss,
            anilist,
            screenshot

          base: header
          base_indepth: no
          base_hireable: no

          plugin_introduction: yes

          plugin_lines: yes
          plugin_lines_sections: base
          plugin_lines_repositories_limit: 5
          plugin_lines_history_limit: 2

          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_stars: yes
          plugin_stars_limit: 1

          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: icons

          plugin_anilist: yes
          plugin_anilist_user: adi2603
          plugin_anilist_medias: manga
          plugin_anilist_sections: favorites,characters
          plugin_anilist_limit: 1
          plugin_anilist_limit_characters: 1

          plugin_rss: yes
          plugin_rss_source: https://news.ycombinator.com/rss
          plugin_rss_limit: 4
