name: Github Metrics

on:
  workflow_dispatch:
  push:
    branches: [master, main]
  schedule:
    - cron: 30 6 * * * # Runs daily at 12:00 AM IST

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate Batman-fusion metrics
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics-${{ github.ref_name }}.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_message: "🦇 Metrics out of the shadows!"
          user: EchoSingh

          # Inject custom CSS: Batman fusion + Comic Sans
          extras_css: |
            /* Black background + Comic Sans font throughout */
            svg {
              background-color: #000000;
              font-family: "Comic Sans MS", "Comic Sans", cursive, sans-serif;
            }

            /* Header: Batman yellow */
            .header {
              fill: #FFD700;
            }
            .header-title,
            .header-subtitle {
              fill: #FFD700;
              font-family: "Comic Sans MS", cursive;
            }

            /* Main text: soft gray for readability */
            .text-primary,
            .text-secondary,
            .text-tertiary {
              fill: #A9A9A9;
              font-family: "Comic Sans MS", cursive;
            }

            /* Icons and accent elements: Batman yellow */
            .icon,
            .icon * {
              fill: #FFD700;
            }

            /* Card backgrounds: very dark gray with subtle gold border */
            .card {
              fill: #1f1f1f;
              stroke: #FFD700;
              stroke-width: 1;
              rx: 6;
              ry: 6;
            }

            /* Subtle drop shadow on cards */
            .card-shadow {
              filter: drop-shadow(2px 2px 4px rgba(0, 0, 0, 0.5));
            }

          config_display: medium
          config_padding: "0,10"
          config_timezone: Asia/Kolkata

          base: header
          base_indepth: no
          base_hireable: no

          plugin_introduction: yes

          plugin_lines: yes
          plugin_lines_sections: base
          plugin_lines_repositories_limit: 5
          plugin_lines_history_limit: 2

          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_stars: yes
          plugin_stars_limit: 1

          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: icons

          plugin_anilist: yes
          plugin_anilist_user: adi2603
          plugin_anilist_medias: manga
          plugin_anilist_sections: favorites,characters
          plugin_anilist_limit: 1
          plugin_anilist_limit_characters: 1

          plugin_rss: yes
          plugin_rss_source: https://news.ycombinator.com/rss
          plugin_rss_limit: 4

          config_order: |
            introduction,
            base.header,
            base.activity+community,
            base.repositories,
            habits,
            achievements,
            lines,
            wakatime,
            stars,
            isocalendar,
            topics,
            rss,
            people,
            anilist,
            screenshot
