name: Github Metrics

on:
  workflow_dispatch:
  push:
    branches: [master, main]
  schedule:
    - cron: 30 6 * * * # Runs daily at (12:00 AM IST)

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics-${{ github.ref_name }}.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_message: "👾👾👾👾"

          # Base configuration
          base: activity, community, repositories, header
          base_indepth: no
          base_hireable: no

          # Plugin: Intro
          plugin_introduction: yes

          # Plugin: Personality
          plugin_16personalities: yes
          plugin_16personalities_url: https://www.16personalities.com/profiles/7fd4a3833c7be
          plugin_16personalities_sections: personality, profile, traits
          plugin_16personalities_scores: yes

          # Plugin: Lines
          plugin_lines: yes
          plugin_lines_sections: base
          plugin_lines_repositories_limit: 5
          plugin_lines_history_limit: 2

          # Plugin: WakaTime
          plugin_wakatime: yes
          plugin_wakatime_sections: time, languages, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}

          # Plugin: Achievements
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_only: developer, forker, stargazer, deployer
          plugin_achievements_display: compact
          

          # Plugin: Stargazers
          plugin_stargazers: yes
          plugin_stargazers_charts: yes

          # Plugin: Isocalender
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # Plugin: Stars
          plugin_stars: yes
          plugin_stars_limit: 1

          #Plugin topics
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: icons

          
          #website quote
          plugin_screenshot: yes
          plugin_screenshot_title: XKCD of the day
          plugin_screenshot_url: https://xkcd.com
          plugin_screenshot_selector: "#comic img"

          #plugin reaction
          plugin_reactions: yes
          plugin_reactions_limit: 100
          plugin_reactions_details: percentage


          # Hobbies
          # Anime 
          plugin_anilist: yes
          plugin_anilist_user: adi2603
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, watching
          plugin_anilist_limit: 2


          #plugin music
          plugin_music: yes
          plugin_music_provider: youtube
          plugin_music_playlist: https://music.youtube.com/playlist?list=PLd2ArdZjOMpYqzmDw-LwaDDAzHVEadXF0

          # Peoples
          plugin_people: yes
          plugin_people_types: followers

          #leetcode
          #plugin_leetcode_user: adityarathore2606
          #plugin_leetcode: yes
          #plugin_leetcode_sections: solved, skills, recent
          
          plugin_gists_user: EchoSingh
          plugin_gists: yes

          #rss
          plugin_rss: yes
          plugin_rss_source: https://news.ycombinator.com/rss
          plugin_rss_limit: 4

          #chess
          plugin_chess: yes
          plugin_chess_token: ${{ secrets.CHESS_TOKEN }}
          plugin_chess_platform: lichess.org
          plugin_chess_user: Rathore26
          

          # Configuration order
          config_order: |
            introduction,
            16personalities,
            base.header,
            base.activity+community,
            base.repositories,
            achievements,
            lines,
            wakatime,
            stars,
            stargazers,
            isocalendar,
            topics,
            gists,
            rss,
            screenshot,
            reactions,
            people,
            anilist,
            chess,
            music
