name: Github Metrics

on:
  workflow_dispatch:
  push:
    branches: [master, main]
  schedule:
    - cron: 30 6 * * * # Runs daily at 12:00 AM IST

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate Catppuccin-themed metrics
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics-${{ github.ref_name }}.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_message: "☕️ Metrics brewed fresh!"
          user: EchoSingh

          # Inject custom CSS to apply Catppuccin Mocha palette
          extras_css: |
            /* Background */
            svg { background-color: #1e1e2e; }

            /* Header background and title text */
            .header {
              fill: #fab387;
            }
            .header-title, .header-subtitle {
              fill: #fab387;
            }

            /* Primary text color */
            .text-primary, .text-secondary, .text-tertiary {
              fill: #cdd6f4;
            }

            /* Icons and accent elements */
            .icon, .icon * {
              fill: #fab387;
            }

            /* Card backgrounds (if any) */
            .card {
              fill: #2e2e3e;
            }

          config_display: medium
          config_padding: "0,10"
          config_timezone: Asia/Kolkata

          base: header
          base_indepth: no
          base_hireable: no

          plugin_introduction: yes

          plugin_lines: yes
          plugin_lines_sections: base
          plugin_lines_repositories_limit: 5
          plugin_lines_history_limit: 2

          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no

          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, stargazer, deployer, member, maintainer, developer,
            scripter, explorer, infographile
          plugin_achievements_display: compact
          plugin_achievements_threshold: X

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_stars: yes
          plugin_stars_limit: 1

          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: icons


          plugin_anilist: yes
          plugin_anilist_user: adi2603
          plugin_anilist_medias: manga
          plugin_anilist_sections: favorites,characters
          plugin_anilist_limit: 1
          plugin_anilist_limit_characters: 1

          plugin_rss: yes
          plugin_rss_source: https://news.ycombinator.com/rss
          plugin_rss_limit: 4


          config_order: |
            introduction,
            base.header,
            base.activity+community,
            base.repositories,
            habits,
            achievements,
            lines,
            wakatime,
            stars,
            isocalendar,
            topics,
            rss,
            people,
            anilist,
            screenshot
