name: snake-grid

on:
  workflow_dispatch:
  push:
    branches: [master, main]
  schedule:
    - cron: 30 6 * * * # Runs daily at (12:00 AM IST)
    
jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake1.svg
            dist/snake2.svg?palette=github-dark
            dist/snake-cool.svg?color_snake=#36BCF7FF&color_dots=#3c7dd9,#4b91f1,#64a1f4,#8dbdff,#bfd6f6
          
      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
